name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v2

      # Налаштування Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Збірка Docker образів
      - name: Build Docker images and run Unit Tests
        run: |
          docker compose build

      # Запуск інтеграційних тестів
      - name: Run Integration Tests
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
        continue-on-error: false
