name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 8080:8080
          - 8090:8090

    steps:
      # Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v2

      # Налаштування Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Збірка Docker образів
      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml build

      # Запуск юніт-тестів
      - name: Run Unit Tests
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml run test

      # Запуск інтеграційних тестів
      - name: Run Integration Tests
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
        continue-on-error: false
